flaskblog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, Length

class PostForm(FlaskForm):

    #Validator : optional allows empty field
    title = StringField('Title',
                           validators=[DataRequired(),Length(min=1)])

    content = TextAreaField('Content',
                        validators=[DataRequired(),Length(min=3)])

    submit = SubmitField('Post!')

flaskblog/posts/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from flaskblog import db
from flaskblog.models import Post
from flaskblog.posts.forms import PostForm

posts = Blueprint('posts', __name__)


@posts.route("/post/new" , methods=['GET', 'POST'])
@login_required
def create_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('You have created a new post!', 'success')

        return redirect(url_for('main.home')) 

    return render_template('create_post.html',title='New Post', form=form, legend='Create New Post')

@posts.route("/post/<int:post_id>" , methods=['GET', 'POST'])
@login_required
def post(post_id):
    post = Post.query.get_or_404(post_id)
    form = PostForm()

    if request.method == "GET":        
        form.title.data = post.title
        form.content.data = post.content

    return render_template('post.html',title=post.title, post=post,form=form)

@posts.route("/post/<int:post_id>/update" , methods=['POST'])
@login_required
def update_post(post_id):

    post = Post.query.get_or_404(post_id)
    form = PostForm()

    # prevent /update directly
    if current_user != post.author:
        abort(403)

    
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data

        flash('The post is updated!', 'success')
        db.session.commit()
        return redirect(url_for('posts.post',post_id=post.id))
        #Not a blank space form
    else:
        flash('Update Failed! Make sure the letter in content is higher than 3','danger')
        return redirect(url_for('posts.post',post_id=post.id))

@posts.route("/post/<int:post_id>/delete" , methods=['POST'])
@login_required
def delete_post(post_id):

    #no form required (just input button)
    # So, No get method, cuz we don't get any input as form type
    post =  Post.query.get_or_404(post_id)

    if current_user != post.author:
        abort(403)

    db.session.delete(post)
    db.session.commit()
    flash('Your post is deleted!','success')
    return redirect(url_for('main.home'))

flaskblog/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from flaskblog import db, bcrypt
from flaskblog.models import User, Post
from flaskblog.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestPasswordForm, ResetPasswordForm)

from flaskblog.users.utils import save_picture, send_reset_mail


users = Blueprint('users', __name__)

@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect('home')

    form = RegistrationForm()
    if form.validate_on_submit():
        
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')

        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()

        flash(f'Account created for {form.username.data}!','success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():

    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    form = LoginForm()
    if form.validate_on_submit():        
        user = User.query.filter_by(email=form.email.data).first()

        if user and bcrypt.check_password_hash(user.password, form.password.data):

            #authenticated user (pass in user (User which has mixin so it can pass 'current_user'))
            login_user(user, remember=form.remember.data)
            flash('You have been logged in!', 'success')
            
            next_page = request.args.get('next')

            # replace redirect(url_for(next_page)) by redirect(next_page)
            return redirect(next_page) if next_page else redirect(url_for('main.home'))      
        
        else:
            flash('Login Unsuccessful. Please check username and password', 'danger')

    return render_template('login.html', title='Login', form=form)

@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))

@users.route("/account" , methods=['GET', 'POST'])
@login_required  # If validate by current_user.is_authenticated is True, then allow
def account():
    form = UpdateAccountForm()


    if form.validate_on_submit():

        if form.picture.data:
            image_file_name = save_picture(form.picture.data)
            current_user.image_file = image_file_name
            

        if form.username.data:
            current_user.username = form.username.data


        if form.email.data:
            current_user.email = form.email.data

        flash('Your account has been updated!', 'success')
        #current_user.image_file = 
        db.session.commit()
        return redirect(url_for('users.account'))


    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)

    return render_template('account.html',title='account',image_file=image_file, form=form)


@users.route("/<string:username>")
@login_required
def user_page(username):
    page= request.args.get('page',1,type=int)

    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user).order_by(Post.date_posted.desc()).paginate(per_page=3,page=page)
    return render_template('username_page.html',user=user,posts=posts)
      
# Reset password zone 
@users.route("/request_password", methods=['GET', 'POST'])
def request_password():
    if current_user.is_authenticated:
        return redirect('home')

    form = RequestPasswordForm()
    if form.validate_on_submit():

        user = User.query.filter_by(email=form.email.data).first()
        send_reset_mail(user)
        flash(f'We have sent the request link to {form.email.data}! check it out !','success')

        # How we can save the token ?

        return redirect(url_for('users.login'))

    return render_template('request_password.html', title='Request Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_password(token):
    if current_user.is_authenticated:
        return redirect('home')

    user = User.verify_reset_token(token)

    if user is None:
        flash('This is expired token or invalid token, please try again','danger')
        return redirect('home')

    
    #user = User.query.filter_by(id=user_id).first()
    form = ResetPasswordForm()

    if form.validate_on_submit():     
        user.password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        db.session.commit()
        flash(f'Your password has been changed !','success')


        return redirect(url_for('users.login'))

    return render_template('reset_password.html', title='Reset Password', form=form)

flaskblog/templates/about.html
{% extends "layout.html" %}

{% block content %}
    <h1 class='mb-4'>About us</h1>
{% endblock content %}

flaskblog/templates/account.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ image_file }}">
        <div class="media-body">
          <h2 class="account-heading">{{ current_user.username }}</h2>
          <p class="text-secondary">{{ current_user.email }}</p>
        </div>
      </div>
        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Account Info</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}

                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                        
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.picture.label() }} <br>
                    {{ form.picture(class="form-control-file") }}
                    {% if form.picture.errors %}
                        {% for error in form.picture.errors %}
                            <span class="text-danger">{{ error }}</span></br>
                        {% endfor %}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info mt-3") }}
            </div>
        </form>
    </div>
{% endblock content %}

flaskblog/templates/create_post.html
{% extends "layout.html" %}

{% block content %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            
            <legend class="border-bottom mb-4">{{legend}}</legend>

            <div class='form-group'>
                {{ form.title.label(class="form-control-label") }}
                
                {% if form.title.errors %}
                    {{ form.title(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.title.errors %}
                            <span>{{error}}</span>
                        {% endfor %}
                    </div>

                {% else %}               
                    {{ form.title(class="form-control form-control-lg") }}
                    
                {% endif %}
            </div>

            <div class='form-group'>
                {{ form.content.label(class="form-control-label") }}
                
                {% if form.content.errors %}
                    {{ form.content(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.content.errors %}
                            <span>{{error}}</span>
                        {% endfor %}
                    </div>

                {% else %}             
                    {{ form.content(class="form-control form-control-lg") }}
                    
                {% endif %}
            </div>


        </fieldset>

        <div class='form-group mt-3'>
            {{ form.submit(class='btn btn-outline-info') }}
        </div>
        
    </form>
</div>

{% endblock content %}

flaskblog/templates/home.html
{% extends "layout.html" %}

{% block content %}

{% for post in posts.items %}
    <article class="media content-section">

        <div class="media-body">
            <div class="row">
                <div class = "col-2">
                    <img class="rounded-circle article-img" src= "{{ url_for('static', filename = 'profile_pics/'+post.author.image_file) }}">
                </div>
                <div class = "col-10">
                    <div class="article-metadata">
                        <a class="text-primary mr-2" href="{{ url_for('users.user_page', username=post.author.username) }}">{{ post.author.username }}</a>
                        <small class="text-muted">{{ post.date_posted.strftime("%m/%d/%Y, %H:%M:%S") }}</small>
                    </div>
                    <h1><a class="article-title" href="{{url_for('posts.post', post_id=post.id)}}">{{ post.title }}</a></h1>
                    <p class="article-content">{{ post.content }}</p>
                </div>
            </div>
        </div>

    </article>
{% endfor %}


<!-- page block  -->

<!-- If it's the first page -->
{% if posts.page != 1 %}
    <a class="btn btn-outline-success" href={{ url_for('main.home', page=posts.page - 1) }}>Prev</a>   
{% endif %}

{% for page_num in posts.iter_pages(left_edge=1, right_edge=1,left_current=1) %}              

    {% if page_num %}
        {% if page_num == posts.page %}
            <a class="btn btn-success" href={{ url_for('main.home', page=page_num) }}>{{page_num}}</a>   
        {% else %}
            <a class="btn btn-outline-success" href={{ url_for('main.home', page=page_num) }}>{{page_num}}</a>   

        {% endif %}
    {% else %}
        ..
    {% endif %}
{% endfor %}

<!-- If it is the last page -->
{% if posts.page != posts.pages %}
    <a class="btn btn-outline-success" href={{ url_for('main.home', page=posts.page + 1) }}>Next</a>   
{% endif %}

{% endblock content %}

flaskblog/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!--CSS-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
    
    <!-- title -->
    {% if title %}
    <title>Wallik Blog - {{title}}</title>
    {% else %}
    <title>Wallik Blog</title>
    {% endif %}

    <!-- BS5 (JavaScr)-->  
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>

</head>
<body>

    <!--Nav-->
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
        <a class="navbar-brand mr-4" href="/">Flask Blog</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
            <a class="nav-item nav-link" href="/">Home</a>
            <a class="nav-item nav-link" href="/about">About</a>
            </div>
              <!-- Navbar Right Side -->
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
              <!-- Current user already happens -->
              {% if current_user.is_authenticated %}
                <div class="navbar-nav">
                  <a class="nav-item nav-link" href="/post/new">New post</a>
                  <a class="nav-item nav-link">Hi {{current_user.username}}</a>
                  <a class="nav-item nav-link" href="/account">Account</a>
                  <a class="nav-item nav-link" href="/logout">Logout</a>
                </div>
              {% else %}
                <div class="navbar-nav">
                    <a class="nav-item nav-link" href="/login">Login</a>
                    <a class="nav-item nav-link" href="/register">Register</a>
                </div>
              {% endif %}
                </ul>
            </div>
          </div>
        </nav>


    <main role="main" class="container">
        <div class="row justify-content-center">

          <div class="col-md-7">

            <!--FLASH message!!!-->
            {% with messages = get_flashed_messages(with_categories=true) %}
              {% if messages %}
                {% for category, message in messages %}
                  <div class="alert alert-{{ category }}">
                    {{ message }}
                  </div>
                {% endfor %}
              {% endif %}
            {% endwith %}

            <!-- Content here -->
            {% block content %}{% endblock %}
            
          </div>

          <div class="col-md-4">
            <div class="content-section">
              <h3>Our Sidebar</h3>
              <p class='text-muted'>You can put any information here you'd like.
                <ul class="list-group">
                  <li class="list-group-item list-group-item-light">Latest Posts</li>
                  <li class="list-group-item list-group-item-light">Announcements</li>
                  <li class="list-group-item list-group-item-light">Calendars</li>
                  <li class="list-group-item list-group-item-light">etc</li>
                </ul>
              </p>
            </div>
          </div>
        </div>
      </main>


    <div class="container">
        {% block content_2 %}
    
        {% endblock content_2 %}
    </div>
    
</body>
</html>

flaskblog/templates/login.html
{% extends "layout.html" %}

{% block content %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Sign in</legend>

            <div class='form-group'>
                {{ form.email.label(class="form-control-label") }}
                
                {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{error}}</span>
                        {% endfor %}
                    </div>

                {% else %}               
                    {{ form.email(class="form-control form-control-lg") }}
                    
                {% endif %}
            </div>

            <div class='form-group'>
                {{ form.password.label(class="form-control-label") }}
                
                {% if form.password.errors %}
                    {{ form.password(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                            <span>{{error}}</span>
                        {% endfor %}
                    </div>

                {% else %}             
                    {{ form.password(class="form-control form-control-lg") }}
                    
                {% endif %}
            </div>

            <div class="form-check">
                {{ form.remember(class="form-check-input") }}
                {{ form.remember.label(class="form-check-label") }}
            </div>  

        </fieldset>

        <div class='form-group mt-3'>
            {{ form.submit(class='btn btn-outline-info') }}
        </div>
        
        <small class="text-muted ml-2">
            <a href={{ url_for('users.request_password') }}>Forgot Password?</a>
        </small>
    </form>
</div>

<div class="border-top pt-3">
    <small class="text-muted">
    Don't have an account? 
    <a href="{{ url_for('users.register')}}"> Register</a>
    </small>
</div>


{% endblock content %}

flaskblog/templates/post.html
{% extends "layout.html" %}



{% block content %}


<article class="media content-section">

    
    {% if current_user == post.author %}
        
        <!-- Update Button -->

        <button type="button" class="btn btn-secondary btn-sm mb-3 justify-content-end" data-bs-toggle="modal" data-bs-target="#updateModal">
                Edit <i class="bi bi-pen"></i>
                       
        </button>

            <!-- Delete Button -->
        <button type="button" class="btn btn-danger btn-sm mb-3 justify-content-end" data-bs-toggle="modal" data-bs-target="#deleteModal">
                Delete <i class="bi bi-trash-fill"></i>
        </button>


        <!-- Update Modal -->
        <div class="modal fade" id="updateModal" tabindex="-1" aria-labelledby="updateModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="updateModalLabel">Edit Post ?</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>

                    <!--Work on this Next!-->
                    <div class="modal-body">

                        

                                <img class="rounded-circle article-img" src= "{{ url_for('static', filename = 'profile_pics/'+post.author.image_file) }}">    
                                <div class="article-metadata">
                                    <a class="mr-2" href="#">{{ post.author.username }}</a>
                                    <small class="text-muted">{{ post.date_posted.strftime("%m/%d/%Y, %H:%M:%S") }}</small>
                                </div>

                                <form action="{{url_for('posts.update_post', post_id = post.id )}}" method="POST">
                                    {{ form.hidden_tag() }}
                                    <div class="media-body">    
                                        <!-- Title -->
                                        {{ form.title.label(class="form-control-label") }}
                                        {{ form.title(class="form-control form-control-lg") }}

                                        <!-- Content -->
                                        {{ form.content.label(class="form-control-label") }}                
                                        {% if form.content.errors %}
                                            {{ form.content(class="form-control form-control-lg is-invalid") }}
                                            <!-- Tell all errors -->
                                            <div class="invalid-feedback">
                                                {% for error in form.content.errors %}
                                                    <span>{{error}}</span>
                                                {% endfor %}
                                            </div>                       
                                        {% else %}             
                                            {{ form.content(class="form-control form-control-lg") }}                        
                                        {% endif %}  
                                    </div>                              
                             </div>

                                    <div class="modal-footer">                                    
                                        {{form.submit(class='btn btn-outline-success')}}                       
                                        </form>          
                                    </div>

                </div>
            </div>
        </div>

        <!-- Delete Modal -->
        <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="deleteModalLabel">Delete Post ?</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        This will be permanently deleted..
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <form action="{{url_for('posts.delete_post', post_id = post.id )}}" method="POST">
                            <input type="submit" class="btn btn-danger" value="delete">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

    
    <div class="media-body">
        <img class="rounded-circle article-img" src= "{{ url_for('static', filename = 'profile_pics/'+post.author.image_file) }}">    
        <div class="article-metadata">
            <a class="mr-2" href={{ url_for('users.user_page', username=post.author.username) }}>{{ post.author.username }}</a>
            <small class="text-muted">{{ post.date_posted.strftime("%m/%d/%Y, %H:%M:%S") }}</small>
        </div>
        <h1><a class="article-title" href="#">{{ post.title }}</a></h1>
        <p class="article-content">{{ post.content }}</p>
    </div>

</article>
{% endblock content %}

flaskblog/templates/request_password.html
{% extends "layout.html" %}

{% block content %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Forget the password</legend>

            <div class='form-group'>
                {{ form.email.label(class="form-control-label") }}
                
                {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{error}}</span>
                        {% endfor %}
                    </div>

                {% else %}               
                    {{ form.email(class="form-control form-control-lg") }}
                    
                {% endif %}
            </div>

        </fieldset>

        <div class='form-group mt-3'>
            {{ form.submit(class='btn btn-outline-info') }}
        </div>
        
    </form>
</div>

<div class="border-top pt-3">
    <small class="text-muted">
    Don't have an account? 
    <a href="{{ url_for('users.register')}}"> Register</a>
    </small>
</div>


{% endblock content %}

flaskblog/templates/username_page.html
{% extends "layout2.html" %}

{% block profile %}

        <img class="rounded-circle article-img" src= "{{ url_for('static', filename = 'profile_pics/'+user.image_file) }}">
        <h2>
            <i class="bi bi-person"></i> {{user.username}}
        </h2>
        <p>
            <i class="bi bi-envelope"></i> {{user.email}}
        </p>


{% endblock profile %}

{% block content %}
    {% for post in posts.items %}
        <article class="media content-section">

            <div class="media-body">
                <div class="row">
                    <div class = "col-2">
                        <img class="rounded-circle article-img" src= "{{ url_for('static', filename = 'profile_pics/'+post.author.image_file) }}">
                    </div>
                    <div class = "col-10">
                        <div class="article-metadata">
                            <a class="text-primary mr-2" href="#">{{ post.author.username }}</a>
                            <small class="text-muted">{{ post.date_posted.strftime("%m/%d/%Y, %H:%M:%S") }}</small>
                        </div>
                        <h1><a class="article-title" href="{{url_for('posts.post', post_id=post.id)}}">{{ post.title }}</a></h1>
                        <p class="article-content">{{ post.content }}</p>
                    </div>
                </div>
            </div>

        </article>
    {% endfor %}



    <!-- Button page -->
    {% if posts.page != 1 %}
        <a class="btn btn-outline-success" href={{ url_for('users.user_page', username=user.username, page=posts.page - 1) }}>Prev</a>   
    {% endif %}
    
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1,left_current=1) %}
        {% if page_num %}
            {% if page_num == posts.page %}
                <a class="btn btn-success" href={{ url_for('users.user_page', username=user.username, page=page_num) }}>{{page_num}}</a>   
            {% else %}
            <a class="btn btn-outline-success" href={{ url_for('users.user_page', username=user.username, page=page_num) }}>{{page_num}}</a>   

            {% endif %}
        {% else %}
            ..
        {% endif %}
    {% endfor %}

    {% if posts.page != posts.pages %}
        <a class="btn btn-outline-success" href={{ url_for('users.user_page', username=user.username, page=posts.page + 1) }}>Next</a>   
    {% endif %}

{% endblock content %}